code/routes/admin.php
<?php
Route::get('/', ['as' => 'transaction.data', 'uses' =>  'Admin\\TransactionController@index'])->name('home');
Route::get('/transaction/datatable/', ['as' => 'transaction.datatable', 'uses' =>  'Admin\\TransactionController@transaction_data']);
Route::get('/transaction', ['uses' =>  'Admin\\TransactionController@transaction']);
Route::get('/transaction/{id}', ['uses' =>  'Admin\\TransactionController@transaction_detail']);

code/routes/user.php
<?php

Route::get('/', function ()
{
    return view('web.homepage');
})->name('home');

code/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('captcha', function() {
  return '<p>' . captcha_img() . '</p>';
});
//web
Route::get('/', function(){
  return redirect('/register');
});

### Login Auth ##
// Route::get('/login', 'UserAuths\LoginController@index')->name('index');
// Route::post('/login', 'UserAuths\LoginController@login');
// Route::get('/logout', 'UserAuths\LoginController@logout');


Route::group(['middleware' => 'login.guest'], function () {
    Route::get('/login', 'Web\\WebController@login')->name('index');
    Route::post('/login', 'Web\\WebController@submit_login');
    Route::get('/register', 'Web\\WebController@register');
    Route::post('/register', 'Web\\WebController@submit_register');
});
Route::get('/logout', 'Web\\WebController@logout');


// use middleware user
Route::group(['middleware' => 'login'], function () {
  Route::get('/success', 'Web\\WebController@index');
  Route::get('/introduction', 'Web\\WebController@index');
  Route::get('/virtual-reality', 'Web\\WebController@virtualReality');

  Route::get('/chat', 'Web\\WebController@chat');
  Route::post('chat', 'Web\\ChatController@store')->name('chat.store');
  Route::post('chat/join', 'Web\\ChatController@join')->name('chat.join');
  Route::post('interest/add', 'Web\\InterestPromoController@add')->name('interest.add');
});
// end middleware

//Midtrans
Route::post('/payment-midtrans', ['as'=>'midtrans.notification', 'uses'=> 'Web\\MidtransController@vtweb']);
Route::get('/payment-midtrans/{order_id}', ['as'=>'midtrans.notification', 'uses'=> 'Web\\MidtransController@vtweb']);
Route::post('/payment-midtrans/{order_id}', ['as'=>'midtrans.notification', 'uses'=> 'Web\\MidtransController@vtweb']);
Route::get('/do_payment', 'Web\\PaymentController@do_payment');

Route::post('/midtrans/notification', ['as'=>'midtrans.notification', 'uses'=> 'Web\\MidtransController@notification']);
Route::get('/midtrans/paymentfinish', ['as'=>'midtrans.paymentfinish', 'uses'=> 'Web\\MidtransController@paymentfinish']);
Route::get('/midtrans/paymentunfinish', ['as'=>'midtrans.paymentunfinish', 'uses'=> 'Web\\MidtransController@paymentunfinish']);
Route::get('/midtrans/errorhandle', ['as'=>'midtrans.errorhandle', 'uses'=> 'Web\\MidtransController@errorhandle']);

//static page
Route::get('/about-us', 'Web\\StaticPageController@about_us');
Route::get('/contact-us', 'Web\\StaticPageController@contact_us');
Route::get('/faq', 'Web\\StaticPageController@faq');
Route::get('/term-and-condition', 'Web\\StaticPageController@term_and_condition');

Route::group(['prefix' => 'admin'], function ()
{
    Route::get('/login', 'AdminAuth\\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'AdminAuth\\LoginController@login');
    Route::get('/logout', 'AdminAuth\\LoginController@logout')->name('logout');

    Route::get('/profile', 'Admin\\UsersController@profile');
    
    //master
    Route::get('/users/data', ['as' => 'users-admin.data', 'uses' => 'Admin\\UsersController@anyData']);
    Route::resource('users', 'Admin\\UsersController');

    Route::get('/vouchers/data', ['as' => 'vouchers.data', 'uses' => 'Admin\\VouchersController@anyData']);
    Route::resource('vouchers', 'Admin\\VouchersController');
    Route::post('/vocuhers/randomCode', ['uses' => 'Admin\\VouchersController@randomCode']);
    Route::post('/vocuhers/cekCode', ['uses' => 'Admin\\VouchersController@cekCode']);
    Route::get('vocuhers/export', 'Admin\\VouchersController@csv_export')->name('export');

    
    Route::get('participants/export', 'Admin\\ParticipantsController@csv_export')->name('export.participants');
    Route::get('/participants/data', ['as' => 'participants.data', 'uses' => 'Admin\\ParticipantsController@anyData']);
    Route::resource('participants', 'Admin\\ParticipantsController');


    Route::get('/report/promo-used', ['as' => 'report.promo-used', 'uses' => 'Admin\\ReportPromoController@promo_used']);
    Route::get('/report/promo-used/data', ['as' => 'report.promo-used.data', 'uses' => 'Admin\\ReportPromoController@anyDataUsed']);

    Route::get('/about-us/data', ['as' => 'about-us.data', 'uses' => 'Admin\\AboutUsController@anyData']);
    Route::resource('about-us', 'Admin\\AboutUsController');

});
// test email
Route::get('/email', function(){
  return view('admin.email.test');
});

code/app/Voucher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Voucher extends Model
{
    const STATUS_CONFIRM_PAYMENT = "CONFIRM PAYMENT";
    const STATUS_PENDING         = "PENDING";
    const STATUS_ACCEPTED        = "ACCEPTED";
    const STATUS_PAID            = "PAID";
    const STATUS_DENIED          = "DENIED";
    const STATUS_EXPIRE          = "EXPIRED";
    const STATUS_CANCEL          = "CANCEL";
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'conf_vouchers';

    /**
     * The database primary key value.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['code_voucher', 'email', 'quota', 'remaining_quota', 'arrayPayment', 'status_code', 'status'];

    protected $casts = [
        'arrayPayment' => 'array'
    ];
}

code/app/Http/Controllers/Admin/VouchersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Voucher;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Config\EmailFunction;
use Illuminate\Http\Request;
use App\Exports\CsvExport;
use Maatwebsite\Excel\Facades\Excel;
use DB;

use Yajra\Datatables\Datatables;

class VouchersController extends Controller
{
    public function __construct()
    {
        header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
        header("Cache-Control: post-check=0, pre-check=0", false);
        header("Pragma: no-cache");

        $this->middleware('auth:admin');
    }

    public function index()
    {
        return view('admin.voucher.index');
    }

    public function create()
    {
        return view('admin.voucher.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'code_voucher' => 'required|unique:conf_vouchers,code_voucher|max:10',
            'email' => 'required',
            'quota' => 'required'
        ]);

        $requestData = $request->all();
        $requestData['remaining_quota'] = $request->quota;

        $voucher = Voucher::create($requestData);

        if ($voucher)
        {
            // send voucher
            app(EmailFunction::class)->send_vouchers($voucher);

            $notification = array(
                'message' => 'Success Send Voucher to '.$voucher->email,
                'alert-type' => 'success'
            );

            return redirect('admin/vouchers')->with($notification);
        }
        else
        {
            $notification = array(
                'message' => 'Failed create data!',
                'alert-type' => 'error'
            );

            return back()->with($notification);
        }
    }

    public function show($id)
    {
        $Voucher = Voucher::findOrFail($id);

        return view('admin.voucher.show', compact('Voucher'));
    }

    public function edit($id)
    {
        $voucher = Voucher::findOrFail($id);

        return view('admin.voucher.edit', compact('voucher'));
    }

    public function update($id, Request $request)
    {
        $updated = Voucher::findOrFail($id);

        $request->validate([
            'address' => 'required',
            'url' => 'required',
            'phone' => 'required'
        ]);

        $requestData = $request->all();

        $updated->update($requestData);

        if ($updated)
        {
            $notification = array(
                'message' => 'Your data updated!',
                'alert-type' => 'success'
            );

            return redirect('admin/vouchers')->with($notification);
        }
        else
        {
            $notification = array(
                'message' => 'Failed to update data!',
                'alert-type' => 'error'
            );

            return back()->with($notification);
        }
    }

    public function destroy($id)
    {
        Voucher::destroy($id);

        $notification = array(
            'message' => 'Success delete',
            'alert-type' => 'success'
        );

        return redirect('admin/vouchers')->with($notification);
    }

    public function anyData()
    {
        DB::statement(DB::raw('set @rownum=0'));
        $voucher = Voucher::select([
            DB::raw('@rownum  := @rownum  + 1 AS rownum'), 'conf_vouchers.*'
        ]);

        return Datatables::of($voucher)
            ->make(true);
    }

    public function randomCode(Request $request)
    {
        //check booking code exsist
        do {
            $random = $this->randomString(5);
            $result = Voucher::where('code_voucher', $random)->count();
        } while ($result > 0);

        return response(['code' => $random],200);
    }

    public function cekCode(Request $request)
    {
        $code = $request->code;
        $check = Voucher::where('code_voucher', $code)->first();
        if(!is_null($check))
        {
            return response(['status' => 400],200);
        }
        else
        {
            return response(['status' => 200],200);
        }
    }

    function csv_export()
    {
		return Excel::download(new CsvExport, 'report-voucher.xlsx');
    }

    function randomString($length)
    {
        $str = "";
        $characters = range('0', '9');
        $max = count($characters) - 1;
        $str .= 'C';
        for ($i = 0; $i < $length; $i++) {
            $rand = mt_rand(0, $max);
            $str .= $characters[$rand];
        }
        return $str;
    }
}

code/resources/views/admin/voucher/create.blade.php
@extends('admin.layout.frame')

@push('breadcrumb')
<nav class="hk-breadcrumb" aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-light bg-transparent">
        <li class="breadcrumb-item"><a href="{{ url('/admin') }}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{{ url('/admin/vouchers') }}">Vouchers</a></li>
        <li class="breadcrumb-item active" aria-current="page">Create Voucher</li>
    </ol>
</nav>
@endpush

@section('title', '| Create Voucher')

@section('content')
    <!-- Container -->
    <div class="container-fluid mt-xl-50 mt-sm-30 mt-15">
        <!-- Row -->
        <div class="row">
            <div class="col-xl-12">
                <section class="hk-sec-wrapper">
                    <h5 class="hk-sec-title" style="margin-bottom: 15px">
                        Create Voucher
                        <span>
                            <a href="{{ url('/admin/vouchers') }}" class="btn bg-dark" style="color: white; float:right">
                                <i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Back
                            </a>
                        </span>
                    </h5>
                    <div class="row">
                        <div class="col-sm">

                            @if ($errors->any())
                                <ul class="alert alert-danger" style="margin-top:15px">
                                    @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            @endif

                            {!! Form::open(['url' => '/admin/vouchers', 'class' => 'form-horizontal', 'files' => true]) !!}

                            @include ('admin.voucher.form')

                            {!! Form::close() !!}
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <!-- /Row -->
    </div>
    <!-- /Container -->
@endsection

@push('script')
    <script>
        @include('admin.layout.notification')
    </script>
@endpush

code/resources/views/admin/voucher/edit.blade.php
@extends('admin.layout.frame')

@push('breadcrumb')
<nav class="hk-breadcrumb" aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-light bg-transparent">
        <li class="breadcrumb-item"><a href="{{ url('/admin') }}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{{ url('/admin/about-us') }}">About Us</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit About Us</li>
    </ol>
</nav>
@endpush

@section('title', '| Edit About Us')

@section('content')

    <!-- Container -->
    <div class="container-fluid mt-xl-50 mt-sm-30 mt-15">
        <!-- Row -->
        <div class="row">
            <div class="col-xl-12">
                <section class="hk-sec-wrapper">
                    <h5 class="hk-sec-title" style="margin-bottom: 15px">
                        Edit About Us
                        <span>
                            <a href="{{ url('/admin/about-us') }}" class="btn bg-dark" style="color: white; float:right">
                                <i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Back
                            </a>
                        </span>
                    </h5>
                    <div class="row">
                        <div class="col-sm">

                            @if ($errors->any())
                                <ul class="alert alert-danger" style="margin-top:15px">
                                    @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            @endif

                            {!! Form::model($aboutus, [
                                'method' => 'PATCH',
                                'url' => ['/admin/about-us', $aboutus->id],
                                'class' => 'form-horizontal',
                                'files' => true
                            ]) !!}

                            @include ('admin.about-us.form', ['submitButtonText' => 'Update'])

                            {!! Form::close() !!}
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <!-- /Row -->
    </div>
    <!-- /Container -->

@endsection

@push('script')
    <script>
        @include('admin.layout.notification')
    </script>
@endpush

code/resources/views/admin/voucher/export.blade.php
<!DOCTYPE html>
<html>
<head>
<title>Report Voucher</title>
</head>
<body>
    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Code Voucher</th>
                <th>Email</th>
                <th>Quota</th>
            </tr>
        </thead>
        <tbody>
        @php $no = 1 @endphp
        @foreach($vouchers as $voucher)
            <tr>
                <td>{{ $no++ }}</td>
                <td>{{ $voucher->code_voucher }}</td>
                <td>{{ $voucher->email }}</td>
                <td>{{ $voucher->quota }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
</body>
</html>

code/resources/views/admin/voucher/form.blade.php
<div class="row">
    <div class="col-md-6 col-sm-12">
        <div class="form-group">
            <label for="title">Code Voucher : </label>&nbsp;<label class="code_required"></label>
            <div class="input-group">
                {{-- <div class="input-group-prepend">
                    <label class="input-group-text" for="code_voucher">C</label>
                </div> --}}
                {!! Form::text('code_voucher', null, ['class' => 'form-control mr-1 code_voucher', 'id' => 'code_voucher', 'required' => 'required']) !!}
                <button type="button" class="btn btn-warning" id="randomCode">Random</button>
                <button type="button" class="btn btn-primary" id="checkCode">Check</button>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-12">
        <div class="form-group">
            <label for="email">Email :</label>
            <div class="input-group">
                {!! Form::text('email', null, ['class' => 'form-control']) !!}
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-12">
        <div class="form-group">
            <label for="quota">Quota :</label>
            <div class="input-group">
                {!! Form::text('quota', null, ['class' => 'form-control inputnumber']) !!}
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            {!! Form::submit(isset($submitButtonText) ? $submitButtonText : 'Create', ['class' => 'btn bg-green', 'style' => 'color: white'])!!}
            <input type="reset" value="Clear" class="btn bg-grey" style="color: white">
        </div>
    </div>
</div>

@push('script')
    <script>
        $( document ).ready(function() {
            var url = "{{ url('/admin/vocuhers/randomCode') }}";
            $.ajax({
                type: "POST",
                url: url,
                dataType: "json",
                data: {
                    "_token": '{{ csrf_token() }}'
                },
                success: function(datas)
                {
                    $("#code_voucher").val(datas.code);
                },
                error: function(data)
                {
                    window.location.reload();
                }
            });
        });
        $("#randomCode").click(function ()
        {
            var url = "{{ url('/admin/vocuhers/randomCode') }}";
            $.ajax({
                type: "POST",
                url: url,
                dataType: "json",
                data: {
                    "_token": '{{ csrf_token() }}'
                },
                success: function(datas)
                {
                    $("#code_voucher").val(datas.code);
                },
                error: function(data)
                {
                    window.location.reload();
                }
            });
        });

        $("#checkCode").click(function ()
        {
            var code = $("#code_voucher").val();
            $(".code_required").html(".....");
            // if code null
            if(code == "")
            {
                $(".code_required").css("color", "#d44950").html("Required");
            }
            else
            {
                var url = "{{ url('/admin/vocuhers/cekCode') }}";
                $.ajax({
                    type: "POST",
                    url: url,
                    dataType: "json",
                    data: {
                        "code"  : code,
                        "_token": '{{ csrf_token() }}'
                    },
                    success: function(datas)
                    {
                        if(datas.status == 200)
                        {
                                $(".code_required").css("color", "#4159c3").html("Can Used");
                        }
                        else
                        {
                                $(".code_required").css("color", "#d44950").html("Already Exists");
                        }
                    },
                    error: function(data)
                    {
                        // window.location.reload();
                    }
                }); 
            }
        });

        $(document).on('keydown','.inputnumber', function(e){
            // Allow: backspace, delete, tab, escape, enter and .
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                    // Allow: Ctrl+A
                (e.keyCode == 65 && e.ctrlKey === true) || 
                    // Allow: home, end, left, right, down, up
                (e.keyCode >= 35 && e.keyCode <= 40)) {
                        // let it happen, don't do anything
                        return;
            }
            // Ensure that it is a number and stop the keypress
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });

        var maxWords = 5;
		$('.code_voucher').on('keypress', function(event) {
            $(".code_required").html("");
			var $this, wordcount;
			$this = $(this);
			wordcount = $this.val().length;
            console.log(wordcount);
			if (event.which == 13) {
				event.preventDefault();
				var s = $(this).val();
				$(this).val(s+"\n");
			}
			if (wordcount > maxWords) {
                $(".code_required").css("color", "#d44950").html("Code Voucher maximum 6 characters");
				return false;
			}
		});

    </script>
@endpush

code/resources/views/admin/voucher/index.blade.php
@extends('admin.layout.frame')

@push('breadcrumb')
    <nav class="hk-breadcrumb" aria-label="breadcrumb">
        <ol class="breadcrumb breadcrumb-light bg-transparent">
            <li class="breadcrumb-item"><a href="{{ url('/admin') }}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Voucher</li>
        </ol>
    </nav>
@endpush

@section('title', '| About Us')

@section('content')

    <!-- Container -->
    <div class="container-fluid mt-xl-50 mt-sm-30 mt-15">
        <!-- Row -->
        <div class="row">
            <div class="col-xl-12">
                <section class="hk-sec-wrapper">
                    <h5 class="hk-sec-title" style="margin-bottom: 35px">
                        Voucher
                        <span>
                            <a href="{{ url('/admin/vouchers/create') }}" class="btn bg-success" style="color: white; float:right">
                                <i class="fa fa-plus" aria-hidden="true"></i> Create
                            </a>
                        </span>
                        
                        <span>
                            <a href="{{ url('/admin/vocuhers/export') }}" class="btn bg-info" style="color: white; float:right">
                                <i class="fa fa-download" aria-hidden="true"></i> Export
                            </a>
                        </span>
                    </h5>
                    <div class="row">
                        <div class="col-sm">
                            <div class="table-wrap table-responsive">
                                <table id="voucher" class="table table-bordered table-striped table-saw" cellspacing="0">
                                    <thead align="left">
                                        <tr>
                                            <th width="10%">No</th>
                                            <th width="25%">Voucher Code</th>
                                            <th width="25%">Email</th>
                                            <th width="10%">Quota</th>
                                            <th width="15%">Remaining Quota</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <!-- /Row -->
    </div>
    <!-- /Container -->

@endsection

@push('script')
    <script>
        var oTable;
        $(document).ready(function()
        {
            oTable = $('#voucher').DataTable({
                processing: true,
                serverSide: true,
                order:  [[ 0, "asc" ]],
                searching: true,
                //dom: 'Bfrtip',
                //buttons: [
                //    'copy', 'csv', 'excel', 'pdf', 'print'
                //],
                responsive: true,
                ajax: '{!! route('vouchers.data') !!}',
                columns: [
                    { data: "rownum", name: "rownum", searchable: false },
                    { data: 'code_voucher', name: 'code_voucher'},
                    { data: 'email', name: 'email' },
                    { data: 'quota', name: 'quota' },
                    { data: 'remaining_quota', name: 'remaining_quota' }
                ]
            });
        });

        function deleteData(id)
        {
            swal({
                title: "Are you sure?",
                text: "You will not be able to recover this imaginary data!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes!",
                cancelButtonText: "No!",
                closeOnConfirm: false,
                closeOnCancel: false
            }, function (isConfirm) {
                if (isConfirm) {
                    $.ajax({
                        type: "POST",
                        url: '{{ route("about-us.index") }}/' + id + '?' + $.param({"_token" : '{{ csrf_token() }}' }),
                        data: {_method: 'delete'},
                        complete: function (msg) {
                            oTable.draw();
                            swal("Success", "Your data already deleted", "success");
                        }
                    });
                } else {
                    swal("Cancelled", "Your imaginary data is safe :)", "error");
                }
            });
        }

        @include('admin.layout.notification')
    </script>
@endpush